name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: pkg-config libx11-dev libxi-dev libxtst-dev libxcb1-dev libxkbcommon-dev libxkbcommon-x11-dev libxdo-dev
          version: 1.2
      - uses: swatinem/rust-cache@v2
        with:
          shared-key: rust-cache
          cache-all-crates: true
      - run: cargo test --workspace --no-fail-fast
